context:
  version: "2.72"

package:
  name: autoconf
  version: "${{ version }}"

source:
  url: http://ftp.gnu.org/gnu/autoconf/autoconf-${{ version }}.tar.gz
  sha256: afb181a76e1ee72832f6581c0eddf8df032b83e2e0239ef79ebedc4467d92d6e
  patches:
    - 0001-Patch-shebang.patch
    - 0002-Add-use-lib-.-to-auto-scan-header-.in.patch
    # https://www.mail-archive.com/bug-autoconf@gnu.org/msg05487.html
    - 0003-Fix-test-failure-on-macOS-15.1.1.patch

build:
  number: 2
  skip: win

requirements:
  build:
    #  make check requirement:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - libtool
    - make
    - curl
    - help2man
    - gnuconfig
    - m4
    - diffutils
    - texinfo
  host:
    - m4
    - perl 5.*
  run:
    - m4
    - perl 5.*
  ignore_run_exports:
    from_package:
      - perl
      - ${{ compiler('c') }}
      - ${{ compiler('cxx') }}


tests:
  - script:
    - autoconf --help
    - autoreconf --help
    - cat $PREFIX/bin/autom4te | grep -v "build_env"  # [unix]
    - cat $PREFIX/bin/autoupdate | grep -v "build_env"  # [unix]

about:
  homepage: http://www.gnu.org/software/autoconf/
  license: GPL-3.0-or-later
  license_file:
    - COPYING
    - COPYINGv3
    - COPYING.EXCEPTION
  summary: Extensible M4 macros that produce shell scripts to configure software source code packages.
  description: |
    Autoconf is a tool for producing shell scripts that automatically configure
    software source code packages to adapt to many kinds of Posix-like systems.
    The configuration scripts produced by Autoconf are independent of Autoconf
    when they are run, so their users do not need to have Autoconf.
  documentation: https://www.gnu.org/software/autoconf/manual/autoconf.html
  repository: http://git.sv.gnu.org/r/autoconf.git

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - mingwandroid
